### PR TITLE
BIG UPDATE, VIEW ADJUSTED TO WORK FOR MOBILE

### PR DESCRIPTION
**Pull request by Icey67**
# **I'VE DONE ANOTHER THING ON GITHUB :D**
To @Celeaxy's recommendation, I learned how to use media calls and adjusted everything accordingly for mobile devices!

## Added/Adjusted:
- Added: Hamburger menu for tabs when screen width is approximately as wide as a phone
- Adjusted: Font size in general
- Added: Positioning for Text in easter egg sites
- Added: Specification site because yes (inspiration from @eveee00 as per usual)

And probably some other things I am not willing to list here :P
shipit

### CODE REVIEW

**Comment by Icey67** [comment]
well, "learned" how to do media calls is a strong word 😬

**Review by eveee00 — COMMENTED** [review]
Looks good to me :)

**Comment by Icey67** [comment]
image
merging :P

**Comment by eveee00** [comment]
:shipit:

**Pull request merged**
